#!/bin/bash

# General Icons
LOADING=􀖇
APPLE=􀣺
PREFERENCES=􀺽
ACTIVITY=􀒓
LOCK=􀒳
BELL=􀋚
BELL_DOT=􀝗

# Claude usage Icons
CLAUDE=􀆿
CLAUDE_TOKENS=􀅴
CLAUDE_COST=􀖎
CLAUDE_BURN=􀋥
CLAUDE_RESET=􀐫
CLAUDE_MODELS=􀪬
CLAUDE_HIST=$CLAUDE_MODELS   # stacked-bars glyph, reused for the token history sparkline row
CLAUDE_COST_HIST=$CLAUDE_COST # dollarsign glyph, reused for the daily-cost sparkline row
CLAUDE_DOT=●                 # per-model legend swatch (recolored at runtime)

# Git Icons
GIT_ISSUE=􀍷
GIT_DISCUSSION=􀒤
GIT_PULL_REQUEST=􀙡
GIT_COMMIT=􀡚
GIT_INDICATOR=􀂓

# Spotify Icons
SPOTIFY_BACK=􀊎
SPOTIFY_PLAY_PAUSE=􀊈
SPOTIFY_NEXT=􀊐
SPOTIFY_SHUFFLE=􀊝
SPOTIFY_REPEAT=􀊞

# Yabai Icons
YABAI_STACK=􀏭
YABAI_FULLSCREEN_ZOOM=􀏜
YABAI_PARENT_ZOOM=􀥃
YABAI_FLOAT=􀢌
YABAI_GRID=􀧍

# Battery Icons
BATTERY_100=􀛨
BATTERY_75=􀺸
BATTERY_50=􀺶
BATTERY_25=􀛩
BATTERY_0=􀛪
BATTERY_CHARGING=􀢋

# Volume Icons
VOLUME_100=􀊩
VOLUME_66=􀊧
VOLUME_33=􀊥
VOLUME_10=􀊡
VOLUME_0=􀊣

# WiFi
WIFI_CONNECTED=􀙇
WIFI_DISCONNECTED=􀙈

# svim
MODE_NORMAL=􀂯
MODE_INSERT=􀂥
MODE_VISUAL=􀂿
MODE_CMD=􀂙
MODE_PENDING=􀈏
