#!/usr/bin/env bash

dev_dirs=$(find "$HOME/coding/dev" -mindepth 2 -maxdepth 2 -type d)
default_dirs=("$HOME/.config")

all_dirs=$(echo -e "${dev_dirs}\n${default_dirs[@]}" | awk '!/\.git/')

selected=$(echo -e "$all_dirs" | fzf --layout reverse --prompt "Select a project: " --preview "ls {}" --preview-window=up:30%)

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -s $selected_name -c $selected -d
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t $selected_name
else
    tmux switch-client -t $selected_name
fi

